### ISSUE TITLE
upload speed

### ISSUE THREAD

**Issue by mortada-jafar** [smmsadrnezh/shekan_installer#1]
after install and connected to ocserv.. i get 0.1MPS speed on MCI and run good on Irancell

any feedback can help to run it on MCI?

**Comment by smmsadrnezh** [comment]
Since I cannot reproduce the issue myself, I may not be able to provide specific advice on how to solve the problem. I have heard similar cases from other people using MCI. Additionally, there may be environmental factors or technical limitations that could impact your internet speed and may be impossible to fix.
